# Generated by Django 5.2 on 2025-04-24 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='ERROR', max_length=10)),
                ('source', models.CharField(choices=[('SP', 'Sponsored Products'), ('SB', 'Sponsored Brands'), ('SD', 'Sponsored Display'), ('SQP', 'SQP'), ('LISTENER', 'Listener'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='SYSTEM', max_length=20)),
                ('component', models.CharField(help_text='Specific component or function where error occurred', max_length=100)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional contextual information about the error', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='logger_erro_timesta_8543b5_idx'), models.Index(fields=['level'], name='logger_erro_level_8f2f85_idx'), models.Index(fields=['source'], name='logger_erro_source_b57142_idx')],
            },
        ),
    ]
