def get_expected_header():
    return {
        "str" : ["Product", "Campaign ID", "Ad Group ID", "Keyword ID", "Product Targeting ID", "Campaign Name (Informational only)", "Ad Group Name (Informational only)", "State", "Campaign State (Informational only)", "Bid", "Keyword Text", "Match Type", "Product Targeting Expression", "Customer Search Term", "Impressions", "Clicks", "Click-through Rate", "Spend", "Sales", "Orders", "Units", "Conversion Rate", "ACOS", "CPC", "ROAS"],

        "bulk" : ["Product", "Entity", "Operation", "Campaign ID", "Draft Campaign ID", "Portfolio ID", "Ad Group ID", "Keyword ID", "Product Targeting ID", "Campaign Name", "Campaign Name (Informational only)", "Portfolio Name (Informational only)", "Start Date", "End Date", "State", "Campaign State (Informational only)", "Campaign Serving Status (Informational only)", "Budget Type", "Budget", "Bid Optimisation", "Bid Multiplier", "Bid", "Keyword Text", "Match Type", "Product Targeting Expression", "Resolved Product Targeting Expression (Informational only)", "Ad Format", "Ad Format (Informational only)", "Landing Page URL", "Landing Page ASINs", "Landing Page Type (Informational only)", "Brand Entity ID", "Brand Name", "Brand Logo Asset ID", "Brand Logo URL (Informational only)", "Custom Image Asset ID", "Creative Headline", "Creative ASINs", "Video Media IDs", "Creative Type", "Impressions", "Clicks", "Click-through Rate", "Spend", "Sales", "Orders", "Units", "Conversion Rate", "ACOS", "CPC", "ROAS"],

        "expected_headers_bulk_mb" : ["Product", "Entity", "Operation", "Campaign ID", "Portfolio ID", "Ad Group ID", "Ad ID", "Keyword ID", "Product Targeting ID", "Campaign Name", "Ad Group Name", "Ad Name", "Campaign Name (Informational only)", "Ad Group Name (Informational only)", "Portfolio Name (Informational only)", "Start Date", "End Date", "State", "Brand Entity ID", "Campaign State (Informational only)", "Campaign Serving Status (Informational only)", "Campaign Serving Status Details (Informational only)", "Rule Based Budget Is Processing (Informational only)", "Rule Based Budget Name (Informational only)", "Rule Based Budget Value (Informational only)", "Rule Based Budget ID (Informational only)", "Ad Group Serving Status (Informational only)", "Ad Group Serving Status Details (Informational only)", "Budget Type", "Budget", "Bid Optimisation", "Product Location", "Bid", "Placement", "Percentage", "Keyword Text", "Match Type", "Native Language Keyword", "Native Language Locale", "Product Targeting Expression", "Resolved Product Targeting Expression (Informational only)", "Ad Serving Status (Informational only)", "Ad Serving Status Details (Informational only)", "Landing Page URL", "Landing Page ASINs", "Landing Page Type", "Brand Name", "Consent To Translate", "Brand Logo Asset ID", "Brand Logo URL (Informational only)", "Brand Logo Crop", "Custom Images", "Creative Headline", "Creative ASINs", "Video Asset IDs", "Original Video Asset IDs (Informational only)", "Subpages", "Impressions", "Clicks", "Click-through Rate", "Spend", "Sales", "Orders", "Units", "Conversion Rate", "ACOS", "CPC", "ROAS"],
        "placement" : ["Start Date", "End Date", "Portfolio name", "Currency", "Campaign Name", "Targeting", "Match Type", "Placement Type", "Impressions", "Clicks", "Click-Thru Rate (CTR)", "Cost Per Click (CPC)", "Spend", "Total Advertising Cost of Sales (ACOS)", "Total Return on Advertising Spend (ROAS)", "14 Day Total Sales (â‚¹)", "14 Day Total Orders (#)", "14 Day Total Units (#)", "14 Day Conversion Rate", "14 Day Brand Total Detail Page Views (#)", "14 Day New-to-brand Orders (#)", "14 Day % of Orders New-to-brand", "14 Day New-to-brand Sales (â‚¹)", "14 Day % of Sales New-to-brand", "14 Day New-to-brand Units (#)", "14 Day % of Units New-to-brand", "14 Day New-to-brand Order Rate"],

        "campaign" : ["Start Date", "End Date", "Portfolio name", "Currency", "Campaign Name", "Cost Type", "Placement", "Impressions", "Viewable Impressions", "Clicks", "Click-Thru Rate (CTR)", "Spend", "Cost Per Click (CPC)", "Cost per 1,000 viewable impressions (VCPM)", "Total Advertising Cost of Sales (ACOS)", "Total Return on Advertising Spend (ROAS)", "14 Day Total Sales (â‚¹)", "14 Day Total Orders (#)", "14 Day Total Units (#)", "14 Day Conversion Rate", "View-Through Rate (VTR)", "Click-Through Rate for Views (vCTR)", "Video First Quartile Views", "Video Midpoint Views", "Video Third Quartile Views", "Video Complete Views", "Video Unmutes", "5 Second Views", "5 Second View Rate", "14 Day Branded Searches", "14 Day Detail Page Views (DPV)", "14 Day New-to-brand Orders (#)", "14 Day % of Orders New-to-brand", "14 Day New-to-brand Sales (â‚¹)", "14 Day % of Sales New-to-brand", "14 Day New-to-brand Units (#)", "14 Day % of Units New-to-brand", "14 Day New-to-brand Order Rate", "Total Advertising Cost of Sales (ACOS) â€“ (Click)", "Total Return on Advertising Spend (ROAS) â€“ (Click)", "14 Day Total Sales â€“ (Click)", "14 Day Total Orders (#) â€“ (Click)", "14 Day Total Units (#) â€“ (Click)"]

    }

