# Generated by Django 5.1.4 on 2024-12-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=10)),
                ('geography', models.CharField(default='India', max_length=50)),
                ('email', models.CharField(default='default@example.com', max_length=100)),
                ('title', models.TextField()),
                ('bullet_point_1', models.TextField()),
                ('bullet_point_2', models.TextField()),
                ('bullet_point_3', models.TextField()),
                ('bullet_point_4', models.TextField()),
                ('bullet_point_5', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]

