# Generated manually
import uuid
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amazon_report_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('selected_metrics', models.JSONField(help_text='List of metrics selected for this report')),
                ('group_by', models.JSONField(blank=True, default=list, help_text='Grouping dimensions for the report')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('download_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_stored', models.BooleanField(default=False, help_text='Whether the report data has been stored in the database')),
                ('rows_processed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_reports', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonAdsCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=2048)),
                ('profile_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('FE', 'Far East')], default='EU', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_ads_credentials', to='amazon_ads_reports.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_report_type', models.CharField(help_text='Report type identifier used in Amazon Ads API', max_length=100)),
                ('ad_product', models.CharField(help_text='Ad product type (e.g., SPONSORED_PRODUCTS)', max_length=50)),
                ('metrics', models.JSONField(help_text='List of available metrics for this report type')),
                ('time_unit', models.CharField(default='DAILY', help_text='Time unit for report data', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTermReportData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_id', models.CharField(db_index=True, max_length=255)),
                ('ad_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword_text', models.CharField(blank=True, max_length=255, null=True)),
                ('match_type', models.CharField(blank=True, max_length=50, null=True)),
                ('query', models.TextField(help_text='Customer search term')),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('click_through_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_per_click', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sales_7d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_14d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_30d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_term_data', to='amazon_ads_reports.adsreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_term_data', to='amazon_ads_reports.tenant')),
            ],
            options={
                'verbose_name': 'Search Term Report Data',
                'verbose_name_plural': 'Search Term Report Data',
                'indexes': [models.Index(fields=['tenant', 'date'], name='amazon_ads__tenant__c10cc7_idx'), models.Index(fields=['tenant', 'query'], name='amazon_ads__tenant__8c20bf_idx'), models.Index(fields=['tenant', 'campaign_id'], name='amazon_ads__tenant__d9a02e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10)),
                ('hour', models.IntegerField(default=1, help_text='Hour of day to run (0-23)')),
                ('minute', models.IntegerField(default=0, help_text='Minute of hour to run (0-59)')),
                ('day_of_week', models.IntegerField(blank=True, help_text='Day of week for weekly schedules (0=Monday, 6=Sunday)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly schedules (1-31)', null=True)),
                ('lookback_days', models.IntegerField(default=7, help_text='Number of days to look back for each report')),
                ('selected_metrics', models.JSONField(help_text='List of metrics to include in the report')),
                ('group_by', models.JSONField(blank=True, default=list, help_text='Grouping dimensions for the report')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_report_schedules', to='auth.user')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='amazon_ads_reports.reporttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='amazon_ads_reports.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='amazon_ads__tenant__00efbb_idx'), models.Index(fields=['next_run'], name='amazon_ads__next_ru_c9f01e_idx')],
            },
        ),
        migrations.AddField(
            model_name='adsreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='amazon_ads_reports.reporttype'),
        ),
        migrations.AddField(
            model_name='adsreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_reports', to='amazon_ads_reports.tenant'),
        ),
        migrations.CreateModel(
            name='DailyProductAdsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('portfolio_id', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_id', models.CharField(db_index=True, max_length=255)),
                ('ad_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_id', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_budget_type', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign_budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('campaign_budget_currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('campaign_status', models.CharField(blank=True, max_length=50, null=True)),
                ('advertised_asin', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('advertised_sku', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('click_through_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_per_click', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('units_sold_clicks_30d', models.IntegerField(default=0)),
                ('units_sold_same_sku_30d', models.IntegerField(default=0)),
                ('sales_1d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_7d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_14d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_30d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('attributed_sales_same_sku_30d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchases_1d', models.IntegerField(default=0)),
                ('purchases_7d', models.IntegerField(default=0)),
                ('purchases_14d', models.IntegerField(default=0)),
                ('purchases_30d', models.IntegerField(default=0)),
                ('purchases_same_sku_30d', models.IntegerField(default=0)),
                ('units_sold_other_sku_7d', models.IntegerField(default=0)),
                ('sales_other_sku_7d', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_ads_data', to='amazon_ads_reports.adsreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_ads_data', to='amazon_ads_reports.tenant')),
            ],
            options={
                'verbose_name': 'Daily Product Ads Data',
                'verbose_name_plural': 'Daily Product Ads Data',
                'unique_together': {('tenant', 'date', 'campaign_id', 'advertised_asin')},
                'indexes': [models.Index(fields=['tenant', 'date'], name='amazon_ads__tenant__e79de4_idx'), models.Index(fields=['tenant', 'campaign_id'], name='amazon_ads__tenant__a2eaed_idx'), models.Index(fields=['tenant', 'advertised_asin'], name='amazon_ads__tenant__7d6cd9_idx'), models.Index(fields=['tenant', 'advertised_sku'], name='amazon_ads__tenant__e84c8a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='amazonadscredential',
            index=models.Index(fields=['profile_id'], name='amazon_ads__profile_e0c9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonadscredential',
            index=models.Index(fields=['tenant', 'is_active'], name='amazon_ads__tenant__e3a4b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='amazonadscredential',
            unique_together={('tenant', 'profile_id')},
        ),
        migrations.AddIndex(
            model_name='adsreport',
            index=models.Index(fields=['tenant', 'status'], name='amazon_ads__tenant__1dee9a_idx'),
        ),
        migrations.AddIndex(
            model_name='adsreport',
            index=models.Index(fields=['start_date', 'end_date'], name='amazon_ads__start_d_b1dad2_idx'),
        ),
        migrations.AddIndex(
            model_name='adsreport',
            index=models.Index(fields=['amazon_report_id'], name='amazon_ads__amazon__5eb307_idx'),
        ),
    ] 