# Generated by Django 5.2 on 2025-05-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('amazon_ads_reports', '0002_report_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adsreport',
            new_name='amazon_ads__tenant__625e1f_idx',
            old_name='amazon_ads__tenant__1dee9a_idx',
        ),
        migrations.RenameIndex(
            model_name='adsreport',
            new_name='amazon_ads__start_d_f8f3f9_idx',
            old_name='amazon_ads__start_d_b1dad2_idx',
        ),
        migrations.RenameIndex(
            model_name='adsreport',
            new_name='amazon_ads__amazon__11b24f_idx',
            old_name='amazon_ads__amazon__5eb307_idx',
        ),
        migrations.RenameIndex(
            model_name='amazonadscredential',
            new_name='amazon_ads__profile_25a755_idx',
            old_name='amazon_ads__profile_e0c9cd_idx',
        ),
        migrations.RenameIndex(
            model_name='amazonadscredential',
            new_name='amazon_ads__tenant__14c3d5_idx',
            old_name='amazon_ads__tenant__e3a4b4_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyproductadsdata',
            new_name='amazon_ads__tenant__1fbc4c_idx',
            old_name='amazon_ads__tenant__e79de4_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyproductadsdata',
            new_name='amazon_ads__tenant__82096c_idx',
            old_name='amazon_ads__tenant__a2eaed_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyproductadsdata',
            new_name='amazon_ads__tenant__7d8595_idx',
            old_name='amazon_ads__tenant__7d6cd9_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyproductadsdata',
            new_name='amazon_ads__tenant__3bbc96_idx',
            old_name='amazon_ads__tenant__e84c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='amazon_ads__tenant__b56a85_idx',
            old_name='amazon_ads__tenant__00efbb_idx',
        ),
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='amazon_ads__next_ru_1f6629_idx',
            old_name='amazon_ads__next_ru_c9f01e_idx',
        ),
        migrations.RenameIndex(
            model_name='searchtermreportdata',
            new_name='amazon_ads__tenant__9d417d_idx',
            old_name='amazon_ads__tenant__c10cc7_idx',
        ),
        migrations.RenameIndex(
            model_name='searchtermreportdata',
            new_name='amazon_ads__tenant__cde44b_idx',
            old_name='amazon_ads__tenant__8c20bf_idx',
        ),
        migrations.RenameIndex(
            model_name='searchtermreportdata',
            new_name='amazon_ads__tenant__c1cbee_idx',
            old_name='amazon_ads__tenant__d9a02e_idx',
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_report_schedules', to='auth.user'),
        ),
    ]
