# Generated by Django 5.2 on 2025-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads_reports', '0004_alter_adsreport_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='default_group_by',
            field=models.JSONField(blank=True, help_text='Default groupBy dimensions for the report', null=True),
        ),
    ]
