# Generated by Django 5.2 on 2025-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads_reports', '0005_reporttype_default_group_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsreport',
            name='download_url',
            field=models.TextField(blank=True, help_text='Amazon S3 pre-signed URL to download the report', null=True),
        ),
    ]
