# Generated by Django 5.2 on 2025-04-25 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSellerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(max_length=255, unique=True)),
                ('marketplace_id', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=512, null=True)),
                ('access_token', models.CharField(max_length=2048)),
                ('refresh_token', models.CharField(max_length=2048)),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('token_expires_at', models.DateTimeField()),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('FE', 'Far East')], default='FE', max_length=2)),
            ],
            options={
                'verbose_name': 'Amazon Seller Account',
                'verbose_name_plural': 'Amazon Seller Accounts',
                'indexes': [models.Index(fields=['seller_id'], name='amazon_sell_seller__cfdbc9_idx'), models.Index(fields=['token_expires_at'], name='amazon_sell_token_e_e1f604_idx')],
            },
        ),
    ]
