# Generated by Django 5.2 on 2025-05-06 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonselleraccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_seller_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AmazonAdvertisingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.CharField(max_length=255, unique=True)),
                ('auth_code', models.CharField(blank=True, max_length=512, null=True)),
                ('access_token', models.CharField(max_length=2048)),
                ('refresh_token', models.CharField(max_length=2048)),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('token_expires_at', models.DateTimeField()),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('FE', 'Far East')], default='FE', max_length=2)),
                ('scopes', models.TextField(blank=True, help_text='Space-separated list of authorized scopes', null=True)),
                ('seller_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_accounts', to='amazon_seller.amazonselleraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_advertising_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amazon Advertising Account',
                'verbose_name_plural': 'Amazon Advertising Accounts',
                'indexes': [models.Index(fields=['profile_id'], name='amazon_sell_profile_0221a6_idx'), models.Index(fields=['token_expires_at'], name='amazon_sell_token_e_7ae9ca_idx')],
            },
        ),
    ]
