# Generated by Django 5.2 on 2025-05-06 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0002_amazonselleraccount_user_amazonadvertisingaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(help_text='Report ID from Amazon API', max_length=255, unique=True)),
                ('report_type', models.CharField(help_text='Type of report (campaigns, adGroups, etc.)', max_length=100)),
                ('status', models.CharField(default='PENDING', help_text='Report generation status', max_length=50)),
                ('metrics', models.TextField(help_text='Comma-separated list of metrics included in the report')),
                ('start_date', models.DateField(blank=True, help_text='Report start date', null=True)),
                ('end_date', models.DateField(help_text='Report end date')),
                ('segment', models.CharField(blank=True, help_text='Optional segment for grouping data', max_length=100, null=True)),
                ('download_url', models.URLField(blank=True, help_text='URL to download the report', max_length=1024, null=True)),
                ('report_data', models.JSONField(blank=True, help_text='Report data if stored directly', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('advertising_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='amazon_seller.amazonadvertisingaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertising_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertising Report',
                'verbose_name_plural': 'Advertising Reports',
                'indexes': [models.Index(fields=['report_id'], name='amazon_sell_report__34ffe5_idx'), models.Index(fields=['status'], name='amazon_sell_status_5c6160_idx'), models.Index(fields=['report_type'], name='amazon_sell_report__49666a_idx'), models.Index(fields=['created_at'], name='amazon_sell_created_fa749a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this report schedule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this scheduled report', null=True)),
                ('report_type', models.CharField(help_text='Type of report (campaigns, adGroups, etc.)', max_length=100)),
                ('metrics', models.TextField(help_text='Comma-separated list of metrics to include in the report')),
                ('segment', models.CharField(blank=True, help_text='Optional segment for grouping data', max_length=100, null=True)),
                ('date_range', models.CharField(choices=[('last_7_days', 'Last 7 Days'), ('last_30_days', 'Last 30 Days'), ('month_to_date', 'Month to Date'), ('previous_month', 'Previous Month'), ('custom', 'Custom Range')], default='last_7_days', max_length=20)),
                ('custom_start_date', models.DateField(blank=True, help_text='Start date for custom range', null=True)),
                ('custom_end_date', models.DateField(blank=True, help_text='End date for custom range', null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly schedules (1-31)', null=True)),
                ('hour', models.IntegerField(default=0, help_text='Hour of day (0-23)')),
                ('minute', models.IntegerField(default=0, help_text='Minute of hour (0-59)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is active')),
                ('last_run', models.DateTimeField(blank=True, help_text='When this schedule last generated a report', null=True)),
                ('next_run', models.DateTimeField(help_text='When this schedule will next generate a report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertising_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='amazon_seller.amazonadvertisingaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'indexes': [models.Index(fields=['next_run'], name='amazon_sell_next_ru_509a16_idx'), models.Index(fields=['is_active'], name='amazon_sell_is_acti_453455_idx'), models.Index(fields=['frequency'], name='amazon_sell_frequen_6d32cf_idx')],
            },
        ),
    ]
