# Generated by Django 5.2 on 2025-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('file_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('blob_name', models.CharField(blank=True, max_length=255, null=True)),
                ('blob_url', models.URLField(blank=True, max_length=500, null=True)),
                ('local_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('access_count', models.IntegerField(default=0)),
                ('is_blob', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='core_sf_expires_idx'), models.Index(fields=['filename'], name='core_sf_filename_idx')],
            },
        ),
    ]
